### ISSUE TITLE
Dual voice refuses to start up

### ISSUE THREAD

**Issue by Destranis** [Mahmood-Taghavi/dual_voice#12]
Version: 5.2 / newest
Operating system: windows 11
Nvda version: 2024 RC 1

Every time I am trying to switch to Dual voice, using the newest version of NVDA (RC1 20224), I am getting the following error message:
Synthesizer Error  dialog  Could not load the dual_sapi5 synthesizer.
After this dialog, the program takes me back to the list of synthesizers. At this stage, unfortunately the addon is unusable, as we are unable to change settings, and the most important, to run the synthesizer.

**Comment by Mahmood-Taghavi** [comment]
Thanks, now I have updated the dual voice to be compatible with the recently published NVDA 2024.1
