### ISSUE TITLE
Request an update to be compatible with NVDA2024.1

### ISSUE THREAD

**Issue by cary-rowen** [Mahmood-Taghavi/dual_voice#13]
As far as I know, there are people in China who rely heavily on this add-on. Can you update it to be compatible with 2024.1?
Do you need me to help you with some compatibility work?
If you don't have time, I'd love to help, including listing an add-on store.

**Comment by Mahmood-Taghavi** [comment]
Thanks for letting me know. I will release the next version by the end of
this month.

**Comment by Mahmood-Taghavi** [comment]
I just have realeasd the dual voice version 5.3 which is compatible with the recently released NVDA 2024.1

**Comment by cary-rowen** [comment]
Thanks, will you upload it to the add-on store and I can do that for you too.

**Comment by Mahmood-Taghavi** [comment]
Thanks Rowen, Unfortunately, I cannot remember how to do that.
Could you please inform them that a new version is released. Also, if
possible, write here what is the procedure for doing that.
The link to the latest version of the Dual Voice addon is provided below:
https://github.com/Mahmood-Taghavi/dual_voice/releases/download/v5.3/dual_voice-5.3.nvda-addon
Thanks in advance for your help!

**Comment by cary-rowen** [comment]
Hi @Mahmood-Taghavi 

Submitting to the add-on store is very simple, you just need to fill in some of the fields in the form below.

[Submit Add-on](https://github.com/nvaccess/addon-datastore/issues/new?assignees=nvaccess&labels=autoSubmissionFromIssue&projects=&template=registerAddon.yml&title=%5BSubmit+add-on%5D%3A+)
Github Action will automatically create a PR and NV Access will merge the PR.
Trusted contributors can work without confirmation from NV Access, and luckily I am one of the trusted contributors.
I've submitted the add-on for you.

Wish you all the best.

Thanks
