### ISSUE TITLE
error in dual voice setting dialog

### ISSUE THREAD

**Issue by ibrahim-s** [Mahmood-Taghavi/dual_voice#2]
when trying to open dual voice setting dialog, it did not open and I got this error in the log:
Input: kb(laptop):downArrow
IO - speech.speak (07:33:34.767) - MainThread (488):
Speaking [LangChangeCommand ('en'), 'Dual voice', 'subMenu', 'v']
DEBUGWARNING - external:synthDrivers.dual_sapi5.SynthDriver.speak (07:33:34.767) - MainThread (488):
Unsupported speech command: LangChangeCommand ('en')
DEBUG - speech.manager.SpeechManager._handleIndex (07:33:34.777) - MainThread (488):
Unknown index 15, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (07:33:35.888) - winInputHook (5088):
Input: kb(laptop):rightArrow
DEBUG - speech.manager.SpeechManager._handleIndex (07:33:35.967) - MainThread (488):
Unknown index 16, speech probably cancelled from main thread.
IO - speech.speak (07:33:35.987) - MainThread (488):
Speaking [LangChangeCommand ('en'), 'Settings of the Dual voice...', 's', '1 of 3']
DEBUGWARNING - external:synthDrivers.dual_sapi5.SynthDriver.speak (07:33:35.987) - MainThread (488):
Unsupported speech command: LangChangeCommand ('en')
IO - inputCore.InputManager.executeGesture (07:33:37.807) - winInputHook (5088):
Input: kb(laptop):enter
DEBUG - gui.settingsDialogs.__new__ (07:33:37.828) - MainThread (488):
Creating new settings dialog (multiInstanceAllowed:False). State of _instances {}
ERROR - unhandled exception (07:33:37.857) - MainThread (488):
Traceback (most recent call last):
  File "C:\Users\ibra\AppData\Roaming\nvda\addons\dual_voice\globalPlugins\dual_voice_globalPlugin\dialogs.py", line 106, in makeSettings
    key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, voiceRegPath)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ibra\AppData\Roaming\nvda\addons\dual_voice\globalPlugins\dual_voice_globalPlugin\__init__.py", line 64, in <lambda>
    gui.mainFrame.sysTrayIcon.Bind(wx.EVT_MENU , lambda e : gui.mainFrame._popupSettingsDialog(DualVoiceLanguageSettingsDialog), item)
  File "gui\__init__.pyc", line 185, in _popupSettingsDialog
  File "C:\Users\ibra\AppData\Roaming\nvda\addons\dual_voice\globalPlugins\dual_voice_globalPlugin\dialogs.py", line 20, in __init__
    super(DualVoiceLanguageSettingsDialog, self).__init__(parent)
  File "gui\settingsDialogs.pyc", line 155, in __init__
  File "C:\Users\ibra\AppData\Roaming\nvda\addons\dual_voice\globalPlugins\dual_voice_globalPlugin\dialogs.py", line 111, in makeSettings
    key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, voiceRegPath)
FileNotFoundError: [WinError 2] The system cannot find the file specified
By the way I use windows10 1903 and latest nvda
and it happens on installed and portable version of nvda.
regards.

**Comment by Mahmood-Taghavi** [comment]
Hi Ibrahim,
could you please specify which sapi 5 voices do you have on you computer.
Furthermore, could you check whether this error occured with all voices or
not?
Best
Mahmood

**Comment by ibrahim-s** [comment]
Hello
these are the voices in sapi5 in my pc
the only non latin voice between them i think is Laila arabic.
Voice: Microsoft David Desktop - English (United States)
Voice: Microsoft Zira Desktop - English (United States)
Voice: Leila (Arabic) SAPI5 - Infovox3
Voice: heather (USEnglish) SAPI5 - Infovox3
and according to test this issue with other voices, it is not possible for me
because when I choose dual voice synth the voice of David is selected automaticaly
and then when I try to open dual voice setting from nvda menue, nothing happens at all.
greetings.

On 2/29/2020 11:24 AM, Mahmood Taghavi wrote:
Hi Ibrahim,
could you please specify which sapi 5 voices do you have on you computer.
Furthermore, could you check whether this error occured with all voices or
not?
Best
Mahmood

**Comment by ibrahim-s** [comment]
something else I experienced
when I select dual voice synthesiser
then opening voice setting dialog for nvda, and changing the voice of David to Laila or Heather in other words one of the accapella voices
and pressing OK, the voices Laila or Heather does not work, and I have no voice in my computer.
then I have to press nvda+control+r to return to saved configuration to have voice back.
greetings.

On 2/29/2020 11:24 AM, Mahmood Taghavi wrote:
Hi Ibrahim,
could you please specify which sapi 5 voices do you have on you computer.
Furthermore, could you check whether this error occured with all voices or
not?
Best
Mahmood

**Comment by Mahmood-Taghavi** [comment]
I updated the dual voice addon according to your reported issue. 
Please check the new version with Infovox 3 voices and let me know whether they are work or not:
https://github.com/Mahmood-Taghavi/dual_voice/releases/download/v4.3/dual_voice-4.3.nvda-addon

**Comment by Mahmood-Taghavi** [comment]
I am looking forward to getting a test result on this issue with the new released dual voice version 4.3

**Comment by ibrahim-s** [comment]
Hello Mahmoud
I have tested the recent version and it worked like a charm
tested it with all voices including infovox voices and all succeeded 
without any problem
and in all cases the dual voice setting dialog in nvda menu opened this 
time without any problem also
issue really closed
and thank you very much for this beautiful work
best wishes.
